#! usr/bin/perl
#Matthew Digman
use strict;
use warnings;
my $itr=3;
while(1){
	$itr++;
	my $tri=$itr*($itr+1)/2;
	my $pent=(1+sqrt(1+4*2*$tri*3))/6;
	unless($pent=~/\D/){
		my $hex=(1+sqrt(1+4*2*$tri))/4;
		unless($hex=~/\D/){
			print "Found: $tri generated by $itr $pent $hex\n";
			unless($tri==40755||$tri==1533776805){
				exit;
			}
		}
	}
}